SELECT DISTINCT USER_ID, PRODUCT_ID
FROM ONLINE_SALE
WHERE (SELECT COUNT(*) FROM ONLINE_SALE s WHERE s.USER_ID = ONLINE_SALE.USER_ID and s.PRODUCT_ID = ONLINE_SALE.PRODUCT_ID) > 1
ORDER BY USER_ID, PRODUCT_ID DESC;