SELECT DISTINCT PRODUCT.PRODUCT_CODE, ((SELECT SUM(SALES_AMOUNT) FROM OFFLINE_SALE o WHERE o.PRODUCT_ID = OFFLINE_SALE.PRODUCT_ID) * PRODUCT.PRICE)AS PRODUCT_AMOUNT 
FROM OFFLINE_SALE
INNER JOIN PRODUCT
ON OFFLINE_SALE.PRODUCT_ID = PRODUCT.PRODUCT_ID
ORDER BY PRODUCT_AMOUNT DESC, PRODUCT_CODE;