SELECT P.PRODUCT_CODE, SUM(OS.SALES_AMOUNT) * P.PRICE AS PRODUCT_AMOUNT
FROM OFFLINE_SALE OS
INNER JOIN PRODUCT P ON OS.PRODUCT_ID = P.PRODUCT_ID
GROUP BY P.PRODUCT_CODE, P.PRICE
ORDER BY PRODUCT_AMOUNT DESC, PRODUCT_CODE;