SELECT SALES_DATE, PRODUCT_ID, USER_ID, SALES_AMOUNT
FROM (SELECT date_format(n.SALES_DATE, '%Y-%m-%d') AS SALES_DATE, n.PRODUCT_ID, n.USER_ID, n.SALES_AMOUNT
FROM ONLINE_SALE n WHERE SALES_DATE like '2022-03%'
union 
SELECT date_format(f.SALES_DATE, '%Y-%m-%d') AS SALES_DATE, f.PRODUCT_ID, NULL AS USER_ID, f.SALES_AMOUNT
FROM OFFLINE_SALE f WHERE SALES_DATE like '2022-03%') AS t
ORDER BY SALES_DATE, PRODUCT_ID, USER_ID;