SELECT C.CAR_ID, C.CAR_TYPE, C.DAILY_FEE * 30 * (100 - TO_NUMBER(REPLACE(P.DISCOUNT_RATE, '%', ''))) / 100 AS FEE FROM CAR_RENTAL_COMPANY_CAR C, CAR_RENTAL_COMPANY_DISCOUNT_PLAN P
WHERE C.CAR_TYPE = P.CAR_TYPE AND P.DURATION_TYPE = '30일 이상'
AND C.DAILY_FEE * 30 * (100 - TO_NUMBER(REPLACE(P.DISCOUNT_RATE, '%', ''))) / 100 >= 500000 AND 
C.DAILY_FEE * 30 * (100 - TO_NUMBER(REPLACE(P.DISCOUNT_RATE, '%', ''))) / 100 < 2000000
AND C.CAR_ID NOT IN (
                        SELECT CAR_ID 
                        FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY 
                        WHERE (TO_CHAR(START_DATE, 'YYYYMMDD') > '20221031' AND TO_CHAR(START_DATE, 'YYYYMMDD') < '20221201')
                            OR (TO_CHAR(END_DATE, 'YYYYMMDD') > '20221031' AND TO_CHAR(END_DATE, 'YYYYMMDD') < '20221201')
                            OR ( TO_CHAR(START_DATE, 'YYYYMMDD') <= '20221031' AND TO_CHAR(END_DATE, 'YYYYMMDD') >= '20221201'))
                            
                            ORDER BY FEE DESC, CAR_TYPE, C.CAR_TYPE DESC; 