-- 코드를 입력하세요
SELECT I.FOOD_TYPE, I.REST_ID, I.REST_NAME, I.FAVORITES
FROM (SELECT FOOD_TYPE, MAX(FAVORITES) AS FAVORITES
FROM REST_INFO 
GROUP BY FOOD_TYPE) T, REST_INFO I
WHERE T.FAVORITES = I.FAVORITES AND T.FOOD_TYPE = I.FOOD_TYPE
ORDER BY T.FOOD_TYPE DESC