SELECT
    CAR_ID,
    TO_CHAR(AVG_DURATION, 'FM9999990.0') AS AVERAGE_DURATION
FROM (
    SELECT
        CAR_ID,
        ROUND(AVG(END_DATE - START_DATE + 1), 1) AS AVG_DURATION
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    GROUP BY CAR_ID
    HAVING ROUND(AVG(END_DATE - START_DATE + 1), 1) >= 7
)
ORDER BY AVG_DURATION DESC, CAR_ID DESC;
