-- 코드를 입력하세요
SELECT M.MEMBER_NAME, R.REVIEW_TEXT, TO_CHAR(R.REVIEW_DATE, 'YYYY-MM-DD')
FROM (SELECT * FROM (SELECT MEMBER_ID, COUNT(MEMBER_ID) AS CNT
FROM REST_REVIEW 
GROUP BY MEMBER_ID
ORDER BY COUNT(MEMBER_ID) DESC) WHERE ROWNUM <= 1 ) T, 
(SELECT MEMBER_ID, COUNT(MEMBER_ID) AS CNT
FROM REST_REVIEW 
GROUP BY MEMBER_ID
ORDER BY COUNT(MEMBER_ID) DESC) H,
MEMBER_PROFILE M,
REST_REVIEW R
WHERE T.CNT = H.CNT
AND H.MEMBER_ID = M.MEMBER_ID
AND R.MEMBER_ID = H.MEMBER_ID
ORDER BY R.REVIEW_DATE, R.REVIEW_TEXT;

